spring:
  rabbitmq:
    username: ENC(xVNdHkueow2rYO4f0vpxMjQEY91FAFt5)
    password: ENC(R0VW0iaU6gNb5oKWCmufn30/RmA0RCkT/+ComChPtWkvUVuhW77t0FndwdH1yQOs)
    host: ENC(any8EhHoWBXJK5f5bHZ8rhfF3Vfou0+YUsMmNSGmNJC+opswadBZPQ==)
    virtual-host: ENC(xVNdHkueow2rYO4f0vpxMjQEY91FAFt5)
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          group: ${spring.application.name}-${random.value}
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              maxConcurrency: 4
saying:
  all: ${saying.prefix} from ${saying.name}
